theme: minima
title: Awesome Blog Title for Chris
author: Chris
email: cconnor17@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the description for my test blog.  I hope that this
  works.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
